default:

stages:
  - build
  - test
  - fmt
  - lint

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
  stage: build
  before_script:
    - rustc --version
    - cargo --version
  image: rust:latest
  script:
    - echo "Building all artifacts"
    - cargo build --release

test:
  stage: test
  image: rust:latest
  before_script:
    - rustc --version
    - cargo --version
  script:
    - echo "Running unit tests"
    - cargo test --release

pretty:
  stage: fmt
  image: rust:latest
  before_script:
    - rustc --version
    - cargo --version
  script:
    - echo "Running cargo fmt"
    - rustup component add rustfmt
    - cargo fmt --all -- --check

code-quality:
  stage: lint
  image: rust:latest
  before_script:
    - rustc --version
    - cargo --version
  script:
    - echo "Running cargo clippy"
    - rustup component add clippy
    - cargo clippy --release -- -D warnings

python-pretty:
  stage: fmt
  image: python:latest
  script:
    - cd "$CI_PROJECT_DIR/eval"
    - python --version
    - pip install -r requirements.txt
    - black *.py --check

python-quality:
  stage: lint
  image: python:latest
  before_script:
  allow_failure: true
  script:
    - cd "$CI_PROJECT_DIR/eval"
    - python --version
    - pip install -r requirements.txt
    - flake8 *.py
